apiVersion: platform.example.com/v1alpha1
kind: XHelmApp
metadata:
  name: my-nginx-app-v2
  namespace: helm-demo  # NUEVO: XR namespacado
spec:
  parameters:
    appName: "nginx-demo-v2"
    chart: "nginx"
    repository: "https://charts.bitnami.com/bitnami"
    version: "15.1.0"
    namespace: "nginx-demo"
    values:
      image:
        tag: "1.25.0"
      service:
        type: ClusterIP
        port: 80
      replicaCount: 3
      resources:
        limits:
          memory: "256Mi"
          cpu: "200m"
        requests:
          memory: "128Mi"
          cpu: "100m"
  crossplane:  # NUEVO: maquinaria de Crossplane bajo spec.crossplane
    compositionRef:
      name: helmapp-composition-v2
