apiVersion: platform.example.com/v1alpha1
kind: XWebApp
metadata:
  name: my-webapp-xr-v2
  namespace: webapp-demo
spec:
  parameters:
    appName: "demo-app-v2"
    replicas: 3
    image: "nginx:1.25"
    namespace: "webapp-demo"
  crossplane:
    compositionRef:
      name: webapp-composition-v2
    compositionUpdatePolicy: Automatic