apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: webapp-composition
  labels:
    crossplane.io/xrd: xwebapps.platform.example.com
spec:
  compositeTypeRef:
    apiVersion: platform.example.com/v1alpha1
    kind: XWebApp
  
  mode: Pipeline
  
  pipeline:
  - step: resources
    functionRef:
      name: function-go-templating
    input:
      apiVersion: gotemplating.fn.crossplane.io/v1beta1
      kind: GoTemplate
      source: Inline
      inline:
        template: |
          {{ $params := .observed.composite.resource.spec.parameters }}
          ---
          apiVersion: kubernetes.crossplane.io/v1alpha2
          kind: Object
          metadata:
            name: {{ $params.appName }}-namespace
            annotations:
              crossplane.io/external-name: {{ $params.namespace }}
              gotemplating.fn.crossplane.io/composition-resource-name: {{ $params.appName }}-namespace
          spec:
            providerConfigRef:
              name: kubernetes-provider
            forProvider:
              manifest:
                apiVersion: v1
                kind: Namespace
                metadata:
                  name: {{ $params.namespace }}
          ---
          apiVersion: kubernetes.crossplane.io/v1alpha2
          kind: Object
          metadata:
            name: {{ $params.appName }}-configmap
            annotations:
              gotemplating.fn.crossplane.io/composition-resource-name: {{ $params.appName }}-configmap
          spec:
            providerConfigRef:
              name: kubernetes-provider
            forProvider:
              manifest:
                apiVersion: v1
                kind: ConfigMap
                metadata:
                  name: {{ $params.appName }}-config
                  namespace: {{ $params.namespace }}
                data:
                  index.html: |
                    <html>
                    <body>
                      <h1>Hello from Crossplane!</h1>
                      <p>Application: {{ $params.appName }}</p>
                      <p>Managed by Crossplane GitOps Demo</p>
                    </body>
                    </html>
          ---
          apiVersion: kubernetes.crossplane.io/v1alpha2
          kind: Object
          metadata:
            name: {{ $params.appName }}-deployment
            annotations:
              gotemplating.fn.crossplane.io/composition-resource-name: {{ $params.appName }}-deployment
          spec:
            providerConfigRef:
              name: kubernetes-provider
            forProvider:
              manifest:
                apiVersion: apps/v1
                kind: Deployment
                metadata:
                  name: {{ $params.appName }}
                  namespace: {{ $params.namespace }}
                spec:
                  replicas: {{ $params.replicas | default 2 }}
                  selector:
                    matchLabels:
                      app: {{ $params.appName }}
                  template:
                    metadata:
                      labels:
                        app: {{ $params.appName }}
                    spec:
                      containers:
                      - name: web
                        image: {{ $params.image | default "nginx:1.21" }}
                        ports:
                        - containerPort: 80
                        volumeMounts:
                        - name: html
                          mountPath: /usr/share/nginx/html
                      volumes:
                      - name: html
                        configMap:
                          name: {{ $params.appName }}-config
          ---
          apiVersion: kubernetes.crossplane.io/v1alpha2
          kind: Object
          metadata:
            name: {{ $params.appName }}-service
            annotations:
              gotemplating.fn.crossplane.io/composition-resource-name: {{ $params.appName }}-service
          spec:
            providerConfigRef:
              name: kubernetes-provider
            forProvider:
              manifest:
                apiVersion: v1
                kind: Service
                metadata:
                  name: {{ $params.appName }}
                  namespace: {{ $params.namespace }}
                spec:
                  selector:
                    app: {{ $params.appName }}
                  ports:
                  - port: 80
                    targetPort: 80
                  type: ClusterIP