apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: webapp-composition
  labels:
    crossplane.io/xrd: xwebapps.platform.example.com
spec:
  compositeTypeRef:
    apiVersion: platform.example.com/v1alpha1
    kind: XWebApp
  
  resources:
  - name: namespace
    base:
      apiVersion: kubernetes.crossplane.io/v1alpha1
      kind: Object
      spec:
        providerConfigRef:
          name: default
        forProvider:
          manifest:
            apiVersion: v1
            kind: Namespace
            metadata:
              name: placeholder
    patches:
    - type: FromCompositeFieldPath
      fromFieldPath: spec.parameters.namespace
      toFieldPath: spec.forProvider.manifest.metadata.name

  - name: configmap
    base:
      apiVersion: kubernetes.crossplane.io/v1alpha1
      kind: Object
      spec:
        providerConfigRef:
          name: default
        forProvider:
          manifest:
            apiVersion: v1
            kind: ConfigMap
            metadata:
              name: placeholder
              namespace: placeholder
            data:
              index.html: |
                <html>
                <body>
                  <h1>Hello from Crossplane!</h1>
                  <p>Application: PLACEHOLDER</p>
                  <p>Managed by Crossplane GitOps Demo</p>
                </body>
                </html>
    patches:
    - type: FromCompositeFieldPath
      fromFieldPath: spec.parameters.appName
      toFieldPath: spec.forProvider.manifest.metadata.name
      transforms:
      - type: string
        string:
          fmt: "%s-config"
    - type: FromCompositeFieldPath
      fromFieldPath: spec.parameters.namespace
      toFieldPath: spec.forProvider.manifest.metadata.namespace
    - type: FromCompositeFieldPath
      fromFieldPath: spec.parameters.appName
      toFieldPath: spec.forProvider.manifest.data["index.html"]
      transforms:
      - type: string
        string:
          type: Replace
          replace:
            search: "PLACEHOLDER"
            with: "%s"

  - name: deployment
    base:
      apiVersion: kubernetes.crossplane.io/v1alpha1
      kind: Object
      spec:
        providerConfigRef:
          name: default
        forProvider:
          manifest:
            apiVersion: apps/v1
            kind: Deployment
            metadata:
              name: placeholder
              namespace: placeholder
            spec:
              replicas: 2
              selector:
                matchLabels:
                  app: placeholder
              template:
                metadata:
                  labels:
                    app: placeholder
                spec:
                  containers:
                  - name: web
                    image: nginx:latest
                    ports:
                    - containerPort: 80
                    volumeMounts:
                    - name: html
                      mountPath: /usr/share/nginx/html
                  volumes:
                  - name: html
                    configMap:
                      name: placeholder
    patches:
    - type: FromCompositeFieldPath
      fromFieldPath: spec.parameters.appName
      toFieldPath: spec.forProvider.manifest.metadata.name
    - type: FromCompositeFieldPath
      fromFieldPath: spec.parameters.namespace
      toFieldPath: spec.forProvider.manifest.metadata.namespace
    - type: FromCompositeFieldPath
      fromFieldPath: spec.parameters.replicas
      toFieldPath: spec.forProvider.manifest.spec.replicas
    - type: FromCompositeFieldPath
      fromFieldPath: spec.parameters.image
      toFieldPath: spec.forProvider.manifest.spec.template.spec.containers[0].image
    - type: FromCompositeFieldPath
      fromFieldPath: spec.parameters.appName
      toFieldPath: spec.forProvider.manifest.spec.selector.matchLabels.app
    - type: FromCompositeFieldPath
      fromFieldPath: spec.parameters.appName
      toFieldPath: spec.forProvider.manifest.spec.template.metadata.labels.app
    - type: FromCompositeFieldPath
      fromFieldPath: spec.parameters.appName
      toFieldPath: spec.forProvider.manifest.spec.template.spec.volumes[0].configMap.name
      transforms:
      - type: string
        string:
          fmt: "%s-config"

  - name: service
    base:
      apiVersion: kubernetes.crossplane.io/v1alpha1
      kind: Object
      spec:
        providerConfigRef:
          name: default
        forProvider:
          manifest:
            apiVersion: v1
            kind: Service
            metadata:
              name: placeholder
              namespace: placeholder
            spec:
              selector:
                app: placeholder
              ports:
              - port: 80
                targetPort: 80
              type: ClusterIP
    patches:
    - type: FromCompositeFieldPath
      fromFieldPath: spec.parameters.appName
      toFieldPath: spec.forProvider.manifest.metadata.name
    - type: FromCompositeFieldPath
      fromFieldPath: spec.parameters.namespace
      toFieldPath: spec.forProvider.manifest.metadata.namespace
    - type: FromCompositeFieldPath
      fromFieldPath: spec.parameters.appName
      toFieldPath: spec.forProvider.manifest.spec.selector.app
