apiVersion: platform.example.com/v1alpha1
kind: XWebApp
metadata:
  name: my-webapp-xr
  namespace: default
spec:
  parameters:
    appName: "demo-app"
    replicas: 3
    image: "nginx:1.21"
    namespace: "webapp-demo2"
  compositionRef:
    name: webapp-composition