apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- xrds/helmapp-xrd-v2.yaml
- compositions/helmapp-composition-v2.yaml

metadata:
  name: model-creator
  annotations:
    config.kubernetes.io/local-config: "true"

