apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- composite-resources/webapp-xr-v2.yaml

metadata:
  name: user
  annotations:
    config.kubernetes.io/local-config: "true"

