apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xwebapps.platform.example.com
spec:
  group: platform.example.com
  names:
    kind: XWebApp
    plural: xwebapps
    # ⭐ No se definen claimNames - Claims opcionales desde v1.14+
  versions:
  - name: v1alpha1
    served: true
    referenceable: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              parameters:
                type: object
                properties:
                  appName:
                    type: string
                    description: Name of the web application
                  replicas:
                    type: integer
                    description: Number of replicas
                    default: 2
                  image:
                    type: string
                    description: Container image
                    default: "nginx:latest"
                  namespace:
                    type: string
                    description: Target namespace
                    default: "default"
                required:
                - appName
              compositionRef:
                type: object
                properties:
                  name:
                    type: string
                    description: The name of the Composition to use
                required:
                - name
              compositionRevisionRef:
                type: object
                properties:
                  name:
                    type: string
                    description: The name of the CompositionRevision to use
                required:
                - name
              compositionUpdatePolicy:
                type: string
                description: The policy for composition updates
                enum:
                - Automatic
                - Manual
                default: Automatic
            required:
            - parameters
          status:
            type: object
            properties:
              conditions:
                type: array
                items:
                  type: object
              ready:
                type: boolean