apiVersion: apiextensions.crossplane.io/v2
kind: CompositeResourceDefinition
metadata:
  name: xhelmapps.platform.example.com
spec:
  scope: Namespaced  # NUEVO: Recursos namespacados por defecto en v2
  group: platform.example.com
  names:
    kind: XHelmApp
    plural: xhelmapps
  versions:
  - name: v1alpha1
    served: true
    referenceable: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              parameters:
                type: object
                properties:
                  appName:
                    type: string
                    description: Name of the Helm application
                  chart:
                    type: string
                    description: Helm chart name
                    default: "nginx"
                  repository:
                    type: string
                    description: Helm repository URL
                    default: "https://charts.bitnami.com/bitnami"
                  version:
                    type: string
                    description: Chart version
                    default: "15.1.0"
                  namespace:
                    type: string
                    description: Target namespace
                    default: "default"
                  values:
                    type: object
                    description: Helm values
                    x-kubernetes-preserve-unknown-fields: true
                required:
                - appName
              # NUEVO en v2: La maquinaria de Crossplane va bajo spec.crossplane
              crossplane:
                type: object
                properties:
                  compositionRef:
                    type: object
                    properties:
                      name:
                        type: string
                    required:
                    - name
                  compositionRevisionRef:
                    type: object
                    properties:
                      name:
                        type: string
                    required:
                    - name
                  compositionUpdatePolicy:
                    type: string
                    enum:
                    - Automatic
                    - Manual
                    default: Automatic
                  resourceRefs:
                    type: array
                    items:
                      type: object
            required:
            - parameters
          status:
            type: object
            properties:
              conditions:
                type: array
                items:
                  type: object
              ready:
                type: boolean
